services:
  runner:
    build: .
    container_name: tv-eyes-runner
    restart: unless-stopped
    network_mode: "host"

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
